
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blue-market_development

test:
  <<: *default
  database: blue-market_test

production:
  <<: *default
  database: blue-market_production
